A = input('Digite algo: ')
print('É um número? : ', A.isnumeric())
print('É uma letra? : ', A.isalpha())
print('Possui letras ou números? : ', A.isalnum())
print('É um decimal? : ', A.isdecimal())
print('É totalmente maiúsculo? : ', A.isupper())
print('É um espaço? : ', A.isspace())